name: Release

on:
  push:
    branches: [ main ]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  NODE_VERSION: 24

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'watergis/maplibre-gl-legend'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # Required for OIDC
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build packages
        run: |
          pnpm --filter="./packages/**" build

      # OIDC requires npm v11.5.1 or later, so ensure we have the latest npm installed
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
